### PR TITLE
Replace pako with pako-lite

### PR DESCRIPTION
**Pull request by TrySound**
original package contains too much extra stuff.

### CODE REVIEW

**Comment by devongovett** [comment]
We are including exactly the files we need in browserify-zlib, and this patch doesn't seem to change what files are included, so it will end up being the same size. What are the differences between pako and pako-lite?

**Comment by TrySound** [comment]
@devongovett I ignored dist and example folders. They are ~700kb. whole pako package is 900kb.

**Comment by devongovett** [comment]
But they are not included in the browserify build, so it doesn't matter much, right? Yeah you download a little more when installing with npm, but I don't think that's a big deal.

**Comment by TrySound** [comment]
Here is not a big deal. There is not a big deal. And then all packages will be huge. Using it is long waiting til install and 2 seconds coding.

**Comment by TrySound** [comment]
Web should be small on every side, I think.

**Comment by devongovett** [comment]
Tell pako not to include dist and examples in the npm package then (they don't need to be there for anyone, not just browserify-zlib). I don't want to depend on a third party distribution of pako.

**Comment by puzrin** [comment]
`browserify` uses only `require`-ed files, so i don't understand this mess about size optimizations. And i have no plans to remove dist files, because those can be useful for different assets managers. Everything is fine without changes.

**Comment by TrySound** [comment]
@devongovett Documentation contains inline jquery. What if every package will contain jquery in docs?

**Pull request closed without merging**
