### PR TITLE
Upgrade to the latest

### PR DESCRIPTION
**Pull request by dignifiedquire**
This PR does a couple of things that were much needed for us
- bring the code base up to date with node `5.9.1`
- port the tests from node `5.9.1` to mocha as we did not want to import the custom test runner node-core is using
- add linting and cleanup the code
- upgrade to the latest version of pako, which adds dictionary support
- Add browser tests using karma, as browserling did not seem to be working when I last checked

This is a very big change and I understand if you have concerns about this. As @diasdavid already mentioned in #16 we will be needing this module in the forseeable future and maintaining it. Hopefully we can find a solution for that without having to maintain all this in a fork.

### CODE REVIEW

**Comment by fanatid** [comment]
@dignifiedquire great work! Much better than #17!
Is this PR up to date with node 6?

**Comment by diasdavid** [comment]
@fanatid #17 was before we knew that pako was missing the dictionary implementation :) @dignifiedquire did a great job at getting everything done, well tested and did a revamp on browserify-zlib, which we are now using for libp2p+ipfs.

**Comment by fanatid** [comment]
@diasdavid ha, didn't notice that you are also from *Protocol Labs* :)

**Comment by dignifiedquire** [comment]
@fanatid not at the moment, there is not much but some changes seem to have been made from `5.9.1..6.0.0`: https://github.com/nodejs/node/commits/v6.0.0/src/node_zlib.cc

**Comment by jscissr** [comment]
This PR fixes #13, #14, #15, #20, and the` Z_BUF_ERROR` issue is also affecting me. Please merge @devongovett! :+1:

**Comment by diasdavid** [comment]
@jscissr is there anything else you would like to see in this PR for the merge?

**Comment by jscissr** [comment]
No, for me everything seems to work fine.

**Comment by diasdavid** [comment]
what about you, @fanatid , looks good to merge? :)

**Comment by fanatid** [comment]
@diasdavid I can't review all this code, but if this new code compliant with node module (at least with 5.x) and passes all tests from node -- it's good for me.

**Comment by devongovett** [comment]
I like the idea of this pull: the module has gotten kinda old. But I think as much of the code as possible should be a direct copy paste from the node source code, including the tests, as I did originally. It will be much easier to maintain: we can just copy paste again in the future. Thoughts?

**Comment by jscissr** [comment]
I agree with you, I didn't think about that. I actually have some experience with packages of direct copies from node; I created [http-node](https://github.com/jscissr/http-node), which is just a copy from node with minor changes. Also I regularly contribute to [http-parser-js](https://github.com/creationix/http-parser-js), which uses the original node test runner and tests, some tweaks were necessary though.

If you like, I could start working on a new PR that does that. Or do you want to make these changes in this PR @dignifiedquire?

**Comment by dignifiedquire** [comment]
I had to adjust a decent amount of code between node.js core and these changes that's why I moved to a code style I was more comfortable and more productive with. As far as I can tell future updates will most of the time not be just a copy and paste, they need some thought if things apply 1-1 in any case.

**Comment by devongovett** [comment]
What were the reasons for needing to make changes from node core?

**Comment by jscissr** [comment]
One problem is that node core uses ES6 features like arrow functions. Other than that, it should be possible to do without much modification at all.

So the problem is that we need a transpiler (like babel) somewhere in the path. One possibility is to use the `package.json` `browserify.transform` field; the problem is that babelify would need to be added to the dependencies, and it's quite a heavy one. The install size of browserify would double.

An other option is to transpile before publishing to npm, react for example does this. I think this would work.

**Comment by dignifiedquire** [comment]
I think the main file didn't get much changes mostly some imports fixed. The most changes were made in the tests as those needed to be ported away from nides custom testrunner. And the bindings file is written from scratch based on the node c++ version. 

Regarding es6: this should definitely be transpiled before publishing to npm if you need to keep es5 compat.

**Comment by jscissr** [comment]
I think it should be possible to leave the test files nearly unchanged, and simply use a custom test runner that monkey-patches the APIs used by the tests like `readFileSync` or `process.on('exit', ...)`. It is even possible to monkey-patch `process.nextTick` to make the whole test synchronous; and then you only need to require the test file, wrapped in a try/catch. If an error is caught, that means the test failed.

I'm working on a PR to show what I mean.

**Comment by dignifiedquire** [comment]
@devongovett all updated thanks to @jscissr

**Comment by dignifiedquire** [comment]
I've added the built version in `lib` to github for now, so it is installable. Please let me know when you want to merge it then I can remove it before.

**Comment by dignifiedquire** [comment]
ping @devongovett

**Comment by diasdavid** [comment]
🙏

**Comment by dignifiedquire** [comment]
@devongovett any chance of this happening? I am also happy to help maintain this module if you don't have the time/ don't want to. But releasing this would benefit the whole browserify/webpack community, who all use this module for zlib in the browser.

**Comment by haadcode** [comment]
Merging this would be hugely beneficial for the https://github.com/ipfs/js-ipfs project. 

We're currently working towards supporting https://github.com/facebookincubator/create-react-app which doesn't support custom webpack configs. As js-ipfs in itself uses a fork of browserify-zlib, we need to include it in our build tools (https://github.com/dignifiedquire/aegir/blob/master/config/webpack.js#L35). As such, we're not able to have create-react-app compile code that uses js-ipfs, because we can't include the fork :/ I hope this makes sense, but let me know if clarification is needed.

If there's anything I (and we) can do to get closer to merging this, please let us know.

**Comment by devongovett** [comment]
Hey sorry guys. I realized I'm completely failing at maintaining this package. @dignifiedquire I've added you as a collaborator on this repo. If you tell me your npm username, I'll add you there too so you can publish.

I think this PR looks pretty good with the modifications you made to use the original code from node. As I mentioned previously, my main goals for this repo originally were to use as much code from node as possible, and to run the tests without modifications as well. This ensured that the browserify version worked in exactly the same way as node. Would be happy if these goals were followed going forward, but I don't have time to personally maintain it anymore. Thanks in advance!

**Comment by dignifiedquire** [comment]
Thank you @devongovett my npm username is the same `dignifiedquire` :)

**Comment by devongovett** [comment]
Awesome, you have been added.

**Comment by dignifiedquire** [comment]
Thank you, I will prepare the PR to be ready for merge tomorrow and hopefully push out a release then :)

**Comment by devongovett** [comment]
Thanks for doing this @dignifiedquire. Can you also make a PR to browserify and webpack to update their dependencies? I don't think they will pull in the new version automatically because of the way semver works.

https://github.com/substack/node-browserify/blob/master/package.json#L27
https://github.com/webpack/node-libs-browser/blob/master/package.json#L12

**Pull request merged**
